version: "3"

services:
  laravel:
    image: hirb0d/thecliniclaravel:latest
    volumes:
      - theclinicapp:/var/www/html/laravel
    depends_on:
      - mysql
    networks:
      - theclinic

  nginx:
    image: hirb0d/thecliniclaravel_nginx:latest
    volumes:
      - theclinicapp:/var/www/html/laravel
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - laravel
      - mysql
    networks:
      - theclinic

  mysql:
    image: mysql:5
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - theclinicdata:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      MYSQL_SERVICE_NAME: mysql
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: hirbod
      MYSQL_DATABASE: thecliniclaravel
    networks:
      - theclinic

volumes:
  theclinicdata:
  theclinicapp:
networks:
  theclinic:
