version: "3.8"

services:
  nginx:
    image: ghcr.io/hirbod-codes/nginx:1.23.1
    volumes:
      - theclinicapp:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    depends_on:
      - laravel
  laravel:
    image: ghcr.io/hirbod-codes/laravel:latest
    volumes:
      - theclinicapp:/var/www/html
    networks:
      - frontend
      - backend
    depends_on:
      - mysql
  mysql:
    image: ghcr.io/hirbod-codes/mysql:5
    command: mysqld --default-authentication-plugin=mysql_native_password
    tty: true
    volumes:
      - data:/var/lib/mysql
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    environment:
      - MYSQL_SERVICE_NAME=mysql
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_USER_FILE=/run/secrets/MYSQL_USER
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
      - MYSQL_DATABASE=thecliniclaravel
    networks:
      - backend

secrets:
  MYSQL_ROOT_PASSWORD:
    external: true
  MYSQL_USER:
    external: true
  MYSQL_PASSWORD:
    external: true
volumes:
  theclinicapp: {}
  data: {}
networks:
  backend:
    driver: overlay
  frontend:
    driver: overlay
