version: "3.8"

services:
    nginx:
        build:
            context: ./nginx
            target: development
        volumes:
            - ./backend:/var/www/html:rw
            - ./nginx/local_ssl/open_ssl.conf:/nginx/local_ssl/open_ssl.conf:rw
            - ./nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf:rw
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
            - ./nginx/logs:/var/log/nginx:rw
    laravel:
        build:
            context: ./backend
            target: development
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./backend:/var/www/html:rw
            - ./backend/addon.ini:/usr/local/etc/php/conf.d/addon.ini:rw
            - ./backend/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:rw
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:5.2.0
        ports:
            - "1000:80"
        environment:
            - PMA_HOST=mysql
        depends_on:
            - mysql
        networks:
            - backend
    swaggerui:
        container_name: swaggerui
        build:
            context: ./swaggerui
        ports:
            - "678:8080"
        environment:
            BASE_URL: /
            SWAGGER_JSON: /docs/swagger.json
        volumes:
            - ./swaggerui/docs:/docs
        networks:
            - frontend