version: "3.8"

services:
  laravel:
    container_name: laravel
    build:
      context: ./backend
      target: feature-test
    networks:
      - backend
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5
    command: mysqld --default-authentication-plugin=mysql_native_password
    tty: true
    environment:
      - MYSQL_SERVICE_NAME=mysql
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=hirbod
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=thecliniclaravel
    networks:
      - backend

networks:
  backend:
    driver: bridge
