version: "3.8"
services:
    nginx:
        container_name: theclinicnginx
        build:
            context: ./
            dockerfile: Dockerfile_Nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
            - ./docker/log/nginx:/var/log/nginx:rw

            - thecliniclaravel_app:/var/www/html/laravel:rw
            - thecliniclaravel_public:/var/www/html/laravel/public:rw
            - thecliniclaravel_vendor:/var/www/html/laravel/vendor:rw
            - thecliniclaravel_node_modules:/var/www/html/laravel/node_modules:rw
        networks:
            - theclinicbridge
        depends_on:
            - laravel
            - mysql
    laravel:
        container_name: thecliniclaravel
        build:
            context: ./
        volumes:
            - thecliniclaravel_app:/var/www/html/laravel:rw
            - thecliniclaravel_public:/var/www/html/laravel/public:rw
            - thecliniclaravel_vendor:/var/www/html/laravel/vendor:rw
            - thecliniclaravel_node_modules:/var/www/html/laravel/node_modules:rw

            - ./docker/php/addon.ini:/usr/local/etc/php/conf.d/addon.ini:rw
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:rw
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - theclinicbridge
        depends_on:
            - mysql
    mysql:
        container_name: theclinicmysql
        image: mysql:5
        tty: true
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:rw
            - theclinicdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: hirbod
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: thecliniclaravel
            MYSQL_SERVICE_NAME: mysql
        networks:
            - theclinicbridge
    phpmyadmin:
        container_name: theclinicphpmyadmin
        image: phpmyadmin
        ports:
            - "1000:80"
        environment:
            - PMA_HOST=mysql
        depends_on:
            - mysql
        networks:
            - theclinicbridge
volumes:
    thecliniclaravel_app: {}
    thecliniclaravel_public: {}
    thecliniclaravel_vendor: {}
    thecliniclaravel_node_modules: {}
    theclinicdata: {}
networks:
    theclinicbridge:
        driver: bridge
