version: "3.8"
services:
    nginx:
        image: nginx
        container_name: thecliniclaravel_nginx
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/log/nginx:/var/log/nginx:rw

            - .:/var/www/html/backend:rw
            - thecliniclaravel_backend_vendor:/var/www/html/backend/vendor:rw
        networks:
            - thecliniclaravel_bridge
        depends_on:
            - backend
    backend:
        container_name: thecliniclaravel_backend
        build:
            context: ./
        volumes:
            - thecliniclaravel_backend_vendor:/var/www/html/backend/vendor:rw
            - .:/var/www/html/backend:rw

            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:rw
            - ./docker/php/addon.ini:/usr/local/etc/php/conf.d/addon.ini:rw
        networks:
            - thecliniclaravel_bridge
        depends_on:
            - mysql
    mysql:
        container_name: thecliniclaravel_mysql
        image: mysql
        tty: true
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - 3306:3306
        volumes:
            - mysqldata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_SERVICE_NAME: mysql
        networks:
            - thecliniclaravel_bridge
    phpmyadmin:
        container_name: thecliniclaravel_phpmyadmin
        image: phpmyadmin
        ports:
            - "1000:80"
        environment:
            - PMA_ARBITRARY=1
        depends_on:
            - mysql
        networks:
            - thecliniclaravel_bridge
volumes:
    thecliniclaravel_backend_vendor: {}
    mysqldata: {}
networks:
    thecliniclaravel_bridge:
        driver: bridge
