version: "3"

services:
  registry:
    image: 5.182.44.231:5000/registry:2
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /auth:/auth
      - /mnt/registry:/var/lib/registry
    secrets:
      - domain.crt
      - domain.key
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: /run/secrets/domain.crt
      REGISTRY_HTTP_TLS_KEY: /run/secrets/domain.key
    deploy:
      replicas: 1
      labels:
        node.labels.registry: true

  laravel:
    image: 5.182.44.231:5000/hirb0d/thecliniclaravel:latest
    volumes:
      - theclinicapp:/var/www/html/laravel
    depends_on:
      - mysql
    networks:
      - theclinic

  nginx:
    image: 5.182.44.231:5000/hirb0d/thecliniclaravel_nginx:latest
    volumes:
      - theclinicapp:/var/www/html/laravel
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - laravel
      - mysql
    networks:
      - theclinic

  mysql:
    image: 5.182.44.231:5000/mysql:5
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - theclinicdata:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      MYSQL_SERVICE_NAME: mysql
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: hirbod
      MYSQL_DATABASE: thecliniclaravel
    networks:
      - theclinic

volumes:
  theclinicdata:
  theclinicapp:
networks:
  theclinic:
secrets:
  domain.crt:
    external: true
  domain.key:
    external: true
