version: "3"

services:
  laravel:
    image: 5.182.44.231:5000/hirb0d/thecliniclaravel:latest
    volumes:
      - theclinicapp:/var/www/html/laravel
    depends_on:
      - mysql
    networks:
      - theclinic

  nginx:
    image: 5.182.44.231:5000/hirb0d/thecliniclaravel_nginx:latest
    volumes:
      - theclinicapp:/var/www/html/laravel
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - laravel
      - mysql
    networks:
      - theclinic

  mysql:
    image: 5.182.44.231:5000/mysql:5
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - theclinicdata:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      MYSQL_SERVICE_NAME: ${{ DB_HOST }}
      MYSQL_ROOT_PASSWORD: ${{ DB_ROOT_PASSWORD }}
      MYSQL_PASSWORD: ${{ DB_PASSWORD }}
      MYSQL_USER: ${{ DB_USERNAME }}
      MYSQL_DATABASE: ${{ DB_DATABASE }}
    networks:
      - theclinic

volumes:
  theclinicdata:
  theclinicapp:
networks:
  theclinic:
