version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - theclinicapp:/var/www/html/laravel
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    depends_on:
      - laravel
  laravel:
    container_name: laravel
    image: laravel
    volumes:
      - theclinicapp:/var/www/html/laravel
    networks:
      - frontend
      - backend
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    tty: true
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend

volumes:
  theclinicapp: {}
  data: {}
networks:
  backend:
    driver: overlay
  frontend:
    driver: overlay
