version: "3.8"

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
      target: production
    volumes_from:
      - laravel:rw

  laravel:
    build:
      context: ./
      target: production
    volumes:
      - thecliniclaravel_app:/var/www/html/laravel:rw
      - thecliniclaravel_public:/var/www/html/laravel/public:rw
      - thecliniclaravel_vendor:/var/www/html/laravel/vendor:rw
      - thecliniclaravel_node_modules:/var/www/html/laravel/node_modules:rw

  mysql:
    build:
      context: ./
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql-password
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_DATABASE}
    secrets:
      - mysql-root-password
      - mysql-password

volumes:
  thecliniclaravel_app: {}
  thecliniclaravel_public: {}
  thecliniclaravel_vendor: {}
  thecliniclaravel_node_modules: {}

secrets:
  mysql-root-password:
    external: true
  mysql-password:
    external: true
