version: "3.8"

services:
    nginx:
        container_name: theclinicnginx
        ports:
            - "80:80"
            - "443:443"
        networks:
            - theclinicbridge
        depends_on:
            - laravel
            - mysql
    laravel:
        container_name: thecliniclaravel
        networks:
            - theclinicbridge
        depends_on:
            - mysql
    mysql:
        container_name: theclinicmysql
        image: mysql:5
        command: mysql --default-authentication-plugin=mysql_native_password
        tty: true
        volumes:
            - theclinicdata:/var/lib/mysql
        environment:
            MYSQL_SERVICE_NAME: mysql
        networks:
            - theclinicbridge
volumes:
    theclinicdata: {}
networks:
    theclinicbridge:
        driver: bridge
