version: "3.8"

services:
  nginx:
    image: hirb0d/thecliniclaravel_nginx:latest
    build:
      context: ./
      dockerfile: Dockerfile.nginx
      target: production
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
    volumes_from:
      - laravel:rw

  laravel:
    image: hirb0d/thecliniclaravel:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
    volumes:
      - thecliniclaravel_app:/var/www/html/laravel:rw
      - thecliniclaravel_public:/var/www/html/laravel/public:rw
      - thecliniclaravel_vendor:/var/www/html/laravel/vendor:rw
      - thecliniclaravel_node_modules:/var/www/html/laravel/node_modules:rw

  mysql:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}

volumes:
  thecliniclaravel_app: {}
  thecliniclaravel_public: {}
  thecliniclaravel_vendor: {}
  thecliniclaravel_node_modules: {}
