version: "3.8"

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
      target: production
    volumes_from:
      - laravel:rw

  laravel:
    image: "${TESTING_IMAGE}"
    working_dir: /var/www/html/laravel
    volumes:
      - thecliniclaravel_app:/var/www/html/laravel:rw
      - thecliniclaravel_public:/var/www/html/laravel/public:rw
      - thecliniclaravel_vendor:/var/www/html/laravel/vendor:rw
      - thecliniclaravel_node_modules:/var/www/html/laravel/node_modules:rw

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}

volumes:
  thecliniclaravel_app: {}
  thecliniclaravel_public: {}
  thecliniclaravel_vendor: {}
  thecliniclaravel_node_modules: {}
