version: "3.8"

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
      target: development
    volumes:
      - ./:/var/www/html/laravel:rw
      - ./local_ssl/open_ssl.conf:/var/www/html/laravel/local_ssl/open_ssl.conf:rw
      - ./docker/nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./docker/log/nginx:/var/log/nginx:rw

  laravel:
    build:
      context: ./
      target: development
    volumes:
      - ./:/var/www/html/laravel:rw
      - ./docker/php/addon.ini:/usr/local/etc/php/conf.d/addon.ini:rw
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:rw

  mysql:
    image: mysql:5
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
  phpmyadmin:
    container_name: theclinicphpmyadmin
    image: phpmyadmin:5.2.0
    ports:
      - "1000:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - theclinicbridge
