version: "3.8"

services:
    nginx:
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        networks:
            - frontend
        depends_on:
            - laravel
    laravel:
        container_name: laravel
        networks:
            - frontend
            - backend
        depends_on:
            - mysql
    mysql:
        container_name: mysql
        build:
            context: ./mysql
            target: back
        command: mysqld --default-authentication-plugin=mysql_native_password
        tty: true
        volumes:
            - data:/var/lib/mysql
        networks:
            - backend
volumes:
    data: {}
networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
