FROM nginx

WORKDIR /var/www/html/laravel

COPY . .

RUN apt-get update && apt-get install -y openssl

RUN openssl req -x509 -nodes -days 1024 -newkey rsa:2048 -keyout local_ssl/localhost.key -out local_ssl/localhost.crt -config local_ssl/open_ssl.conf -extensions 'v3_req'

COPY local_ssl/localhost.crt /etc/ssl/certs/localhost.crt
COPY local_ssl/localhost.key /etc/ssl/private/localhost.key
