name: build

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy the final application in the host server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set the .env file
        env:
          ENV_FILE: ${{secrets.ENV}}
        run: |
          touch .env
          echo $ENV_FILE | base64 -d > .env

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_FTP_USERNAME }}
          password: ${{ secrets.HOST_FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./application/

      - name: SSH to server and run deploy.sh bash script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: chmod u+x /home/hirbod/application/deploy.sh && /home/hirbod/application/deploy.sh
