name: build

on:
  workflow_run:
    workflows: [test]
    types: [completed]
  workflow_dispatch:

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: exit 0

  build:
    name: Deploy the final application in the host server
    runs-on: ubuntu-latest
    needs: [on-success]

    steps:
      - name: checkout the git repo
        uses: actions/checkout@v3

      - name: Login to ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=true
          images: |
            ghcr.io/${{github.repository_owner}}/laravel
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - run: |
          echo "${{ secrets.ENV_FILE }}" >  ./backend/.env
          echo "DB_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >>  ./backend/.env
          echo "DB_USERNAME=${{ secrets.MYSQL_USER }}" >>  ./backend/.env
          echo "DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >>  ./backend/.env

      - name: Build and Push the laravel image to GHCR
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./backend
          tags: ${{ steps.meta.outputs.tags }}
          target: production
          platforms: linux/amd64

      - name: Build and Push the nginx image to GHCR
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./nginx
          tags: ghcr.io/${{github.repository_owner}}/nginx:1.23.1
          target: production
          platforms: linux/amd64

      - name: Build and Push the mysql image to GHCR
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./mysql
          tags: ghcr.io/${{github.repository_owner}}/mysql:5
          platforms: linux/amd64

  ftp:
    name: send new configuration files
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: checkout the git repo
        uses: actions/checkout@v3

      - name: make ftp directory
        run: |
          mkdir ./ftp
          cp ./deploy.sh ./ftp
          cp ./docker-compose.stack.yml ./ftp

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_FTP_USERNAME }}
          password: ${{ secrets.HOST_FTP_PASSWORD }}
          local-dir: ./ftp/
          dangerous-clean-slate: true

  deploy:
    name: Deploy the final application in the host server
    runs-on: ubuntu-latest
    needs: [ftp]

    steps:
      - name: SSH to server and redeploythe application in swarm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_SSH_USERNAME }}
          key: ${{ secrets.HOST_SSH_KEY }}
          port: ${{ secrets.HOST_SSH_PORT }}
          timeout: 60s
          command_timeout: 30m
          script: |
            chmod u+x /home/admin/deploy.sh
            /home/admin/deploy.sh --MYSQL_ROOT_PASSWORD ${{secrets.MYSQL_ROOT_PASSWORD}} --MYSQL_USER ${{secrets.MYSQL_USER}} --MYSQL_PASSWORD ${{secrets.MYSQL_PASSWORD}}

            echo ${{ secrets.MY_GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin 
            docker stack deploy -c /home/admin/docker-compose.stack.yml theclinic --with-registry-auth
