name: ci-cd

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  # FIRST JOB #######################################################################
  build-test-image:
    name: Build Image for Testing
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GHCR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/hirbod-codes/thecliniclaravel:${{ github.run_id }}
          target: tests
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  # NEXT JOB #######################################################################
  unit-tests:
    name: Unit tests in Docker
    needs: [build-test-image]
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Login to ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Unit Testing in Docker
        run: docker run --rm ghcr.io/hirbod-codes/thecliniclaravel:"$GITHUB_RUN_ID" sleep 30 && php artisan initialize && php artisan unit-tests

  # NEXT JOB #######################################################################
  integration-tests:
    name: Integration tests in Compose
    needs: [build-test-image, unit-tests]
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run integration tests with Docker Compose file
        run: |
          export TESTING_IMAGE=ghcr.io/hirbod-codes/thecliniclaravel:"$GITHUB_RUN_ID"
          echo Testing image: "$TESTING_IMAGE"
          docker compose -f docker-compose.test.yml up --exit-code-from laravel

  # NEXT JOB #######################################################################
  build-final-image:
    name: Build Final Image
    needs: [integration-tests, unit-tests]
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata for Final Image Build
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: hirbod-codes/thecliniclaravel,ghcr.io/hirbod-codes/thecliniclaravel
          flavor: |
            latest=false
          tags: |
            type=raw,value=99
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
          # type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}

      - name: Docker Build and Push to GHCR and Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7
