name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  # FIRST JOB #######################################################################
  build-test-image:
    name: Build Image for Testing
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GHCR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/hirbod-codes/${{ github.event.repository.name }}:${{ github.run_id }}
          target: tests
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  # NEXT JOB #######################################################################
  unit-tests:
    name: Unit tests in Docker
    needs: [build-test-image]
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Login to ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Unit Testing in Docker
        run: docker run --rm ghcr.io/hirbod-codes/${{ github.event.repository.name }}:"$GITHUB_RUN_ID" php artisan unit-tests

  # NEXT JOB #######################################################################
  integration-tests:
    name: Integration tests in Compose
    needs: [build-test-image, unit-tests]
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run integration tests with Docker Compose file
        run: |
          export TESTING_IMAGE=ghcr.io/hirbod-codes/${{ github.event.repository.name }}:"$GITHUB_RUN_ID"
          echo Testing image: "$TESTING_IMAGE"
          docker compose -f docker-compose.yml -f docker-compose.test.yml up --exit-code-from laravel

  # NEXT JOB #######################################################################
  store-env:
    name: Store environment variables
    needs: [integration-tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Storing environment variables in Github secret
        run: |
          ls -al ./
          cat .env
          gh secret set ENV < .env
